### ISSUE TITLE
Rename folders

### ISSUE THREAD

**Issue by atygesen** [muhrin/pyos#1]
Renaming a folder, e.g. saying `mv('maibat/', 'aiida/')` just moves the folder `maibat` as a subfodler into `aiida`, instead of renaming it.

Also - minor annoyance, but it requires using the `/`, which as we all know isn't the case in linux :)

**Comment by muhrin** [comment]
Indeed, the folder renaming is a bug.  Will investigate how to make the behaviour like a bash shell.

Where the final `/` is unambigious I can find ways to coerce it.  At best:
```
mv('maibat', 'aiida')
```
_could_ work but only if `maibat` is a folder that exists, i.e. we can infer that the user wants to move a folder to somewhere and that somewhere can only possibly be a folder given that they are moving a folder...
If `maibat` is a file then the trailing `/` on the desination is necessary to communicate whether the user wants to move it to a folder called `aiida/` or to rename it to `aiida`.

**Comment by muhrin** [comment]
Fixed in v0.7.0.
