### ISSUE TITLE
Auto-completion

### ISSUE THREAD

**Issue by atygesen** [muhrin/pyos#2]
@jinchang wants tab autocompletion for completing the strings he's writing. And also, no brackets.

**Comment by muhrin** [comment]
Haha, well I did have tab autocomplete on a previous version.  This is possible with a object, say:
```
cwd.[tab] # completes what's in the current dir
```
but not really fesible as a 'global' autocomplete (apart from maybe something ipython specific).

Brackets I see no way to get rid of more than I've already done.

**Comment by jinchang** [comment]
And I want to have a pink pony.

**Comment by muhrin** [comment]
Auto-completion is now possible via `cwd.<tab>` and `cwd["<tab>` for things that aren't valid python variable names.  Out in version `0.7.1`.
