### ISSUE TITLE
cd into object

### ISSUE THREAD

**Issue by atygesen** [muhrin/pyos#3]
It's possible to do `cd('my_obj')` even though `myobj` is not a directory, but actually an object. This should raise an error.

**Comment by muhrin** [comment]
The following are intentional behaviours of `pyos`:
* `my_obj` (the object) and `my_obj/` (the folder) are allowed to coexist in a folder
* there is no folder creation command thus changing working directory into a new folder is possible
* saving an object in a path causes it to come into existence if it didn't exist already

This leave two (sane and consistent) possibilities for `cd`:

1. Allow passing non directory strings (i.e. those that don't end with `/`) and assume the user wants to change into that directory (even if there is an object of that name already)
2. Require that the user _always_ use the trailing `/`

Checking for an existing object if the user doesn't end with a `/` and forbidding it whilst allowing it if an object of that name doesn't exist is a non-starter.

So would you prefer option 2.?  If so, why?

**Comment by muhrin** [comment]
Bump.  @atygesen any thoughts on this?

**Comment by atygesen** [comment]
Hm.. I'm a fan of not being forced to use the trailing `/`, but I do see the issues with not requiring it. Fundamentally, I'd probably go back and revisit the whole objects name the same as a folder thing - is that really necessary? Or is that too difficult to enforce?

**Comment by muhrin** [comment]
I'm not sure it makes sense revisiting that decision at this point. There are considerable complications that arise with having directories as first class citizens which entail a maintenance overhead and careful management to avoid any negative performance implications.

**Comment by atygesen** [comment]
That's fair. In that case, I think option 2 is my preferred option.

**Comment by muhrin** [comment]
Why's that?  After all, in calling `cd` you're quite clearly stating that what you're passing should be considered a directory.  Roughtly the difference for the user/client code would be (with a file called `test` existing in cwd):

```
# 1
cd('test') # All good
cd('../test/') # All good
```

```
# 2
cd('test')
>>> Exception
cd('test/') # all good
cd(pyos.Path('../test').to_dir()) # all good
```

Now, clearly the second guards you against the situation where you've passed in a file path by accident but the issue this raises is general.  Basically, as this call is entirely clear in the type of path is accepts (i.e. a directory) if `cd` isn't allowed to coerce the path to the right type based on context then no part of `psh` should be able to coerce and the user should _always_ be aware of what type of path they're passing around.  This seems like a rather heavy price to pay in the scripting part of the library (the library methods may be a different story).

What do yo think?

As you suggested, all of this gets easier if we enforce uniqueness of file and directory names so I'm thinking about if there is a way to mitigate one of the main disadvantages that I see, namely that every time an object is saved a database query must be made to make sure the directory exists.  That kills performance for many saves and given this is meant to be a big-data library I think it's worth being careful here.

**Comment by atygesen** [comment]
Well, actually, thinking about it - why should `cd` ever care that an object of that name exists? In some sense, it should only "see" directories, so if I do `cd('test')` into something which is both a folder and a file, `cd` would never care about the fact that an object of name `test` exists, because it should never see it, in the first place?

**Comment by muhrin** [comment]
Yes, that's sort of the philosophy behind option 1, and is therefore the current behaviour.  So, if you agree I'll close this ticket and just leave open the possibility of later finding a way to do file/folder name exclusivity efficiently.

**Comment by atygesen** [comment]
Yeah, let's go with that. I think it works pretty well as it is, it was just a bit akward to `cd` into an object, because I messed something up :)

**Comment by muhrin** [comment]
Great, thanks for the input.  Closing.
