### ISSUE TITLE
Removing folders

### ISSUE THREAD

**Issue by atygesen** [muhrin/pyos#4]
As we discussed, here is a MWE for issues regarding the ModificationError:

`mincepy.exceptions.ModificationError: You're trying to rewrite history, that's not allowed!`

```python
import minkipy
minkipy.workon()

import mincepy
import maibat.clease as mc
from pyos import psh

dirname = 'testdir11/'
psh.cd(dirname)

mc.init_bulk(crystalstructure='fcc', a=3.5)

settings = mincepy.Dict(xc='lda')
mc.save_settings(settings, mc.paths.GENERAL_SETTINGS)

# The following 
group_settings = mc.get_settings(mc.paths.GROUP_SETTINGS)
group_settings.update({'full': mincepy.Dict(isif=3)})
group_settings.save()  # Comment out this line to make the example run

psh.cd('..')
psh.rm(psh.r, dirname)
```

The following library versions were used:
pyos 0.7.1
minkipy 0.2.4
mincepy 0.13.0

**Comment by muhrin** [comment]
This turned out to be an issue in `mincepy`.  It's been fixed now in v0.13.1.  The MWE now works for me without issue.

Please re-open if you feel this isn't fixed.
